[package]

name = "rusty-car"
version = "0.0.1"
authors = [ "Ryan Layne <ryan@cleanlinescollective.com>" ]

[dependencies]

serial = "0.2.0"
time = "0.1.30"
iron = "*"
router = "*"
rustc-serialize = "0.3.15"
websocket = "~0.12.2"
rand = "0.3"